spring:
  application:
    name: dozzari
  config:
    import: optional:file:.env[.properties]

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

server:
  host-url: ${SERVER_HOST_URL}
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-period: ${JWT_ACCESS_TOKEN_EXPIRE_PERIOD}
  refresh-token-expire-period: ${JWT_REFRESH_TOKEN_EXPIRE_PERIOD}
